# Generated by Django 4.1.3 on 2022-12-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournament/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
