# Generated by Django 4.1.3 on 2022-12-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
