# Generated by Django 4.1.3 on 2023-01-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='MVP',
            field=models.IntegerField(default=0),
        ),
    ]
