# Generated by Django 4.1.3 on 2023-01-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0002_user_mvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='is_drawed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
