# Generated by Django 4.1.3 on 2023-01-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0003_alter_invitation_message_alter_invitation_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Tytuł'),
        ),
    ]
