# Generated by Django 4.1.3 on 2023-01-13 16:44

from django.db import migrations, models
import django.db.models.deletion
import tournament_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0003_alter_tournament_is_drawed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tournament_app.team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_teams',
            field=models.IntegerField(validators=[tournament_app.models.power_of_two]),
        ),
    ]
