# Generated by Django 4.1.3 on 2022-12-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0003_alter_team_players_alter_tournament_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_tournament',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='mvp',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_team',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
