# Generated by Django 4.1.3 on 2023-01-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0004_alter_match_winner_alter_tournament_number_of_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
    ]
