# Generated by Django 4.1.3 on 2023-01-10 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0005_alter_invitation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='mvp',
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.IntegerField()),
                ('away_team_score', models.IntegerField()),
                ('match_date', models.DateTimeField()),
                ('MVP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MVP_matches', to=settings.AUTH_USER_MODEL)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournament_app.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournament_app.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament_app.tournament')),
            ],
        ),
    ]
