# Generated by Django 4.1.3 on 2022-12-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0005_alter_team_description_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
