# Generated by Django 4.1.3 on 2023-01-15 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0006_alter_match_away_team_alter_match_home_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='MVP',
        ),
        migrations.AddField(
            model_name='tournament',
            name='MVP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_MVP', to=settings.AUTH_USER_MODEL),
        ),
    ]
