# Generated by Django 4.1.3 on 2022-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0006_alter_team_team_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_leader',
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.IntegerField(default=1, verbose_name='Lider'),
        ),
    ]
