# Generated by Django 4.1.3 on 2023-01-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0006_remove_tournament_mvp_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_started',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
