# Generated by Django 4.1.3 on 2023-01-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0007_tournament_is_finished_tournament_is_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_date',
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_score',
            field=models.IntegerField(default=0),
        ),
    ]
