# Generated by Django 4.1.3 on 2023-01-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0007_remove_match_mvp_tournament_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='won_tournaments',
            field=models.IntegerField(default=0),
        ),
    ]
