# Generated by Django 4.1.3 on 2023-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0008_remove_match_match_date_alter_match_away_team_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_drawed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
